name: attedancekaryawanump
description: A new Flutter project.

version: 1.1.35+41

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  arabic_numbers: ^1.0.0
  build_runner: ^2.1.5
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.3
  external_app_launcher: ^2.0.2
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  flutter_islamic_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^8.2.0
  flutter_native_splash: ^1.2.4
  flutter_polygon: ^0.3.0+2
  fluttertoast: ^8.2.2
  geocoding: ^2.0.1
  geolocator: ^7.6.0
  http: ^0.13.3
  image_picker: ^0.8.2
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  just_audio: ^0.9.31
  mat_month_picker_dialog: ^1.1.0
  provider: ^6.0.1
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  sizer: ^2.0.15
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_image: "assets/images/splashcreen2.png"
  # image: "assets/image/splash.png"
  # (run terminal) flutter pub run flutter_native_splash:create
  # color: "#FFFFFF"
  fullscreen: true
  # fill: true
  # android_disable_fullscreen: true
  # run builder
  # flutter packages pub run build_runner build --delete-conflicting-outputs

flutter_icons:
  # (run terminal) flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  # android: true
  ios: true
  image_path: "assets/images/icons2.png"
  # image_path_ios: "assets/image/icon.png"
  # image_path_android: "assets/image/icon.png"
  adaptive_icon_background: "assets/images/icons2.png"
  adaptive_icon_foreground: "assets/images/icons2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
